### ISSUE TITLE
fix something on README about installation

### ISSUE THREAD

**Issue by asotolongo** [shayonj/pg-osc#43]
In the Installation section 

_Or install it yourself as:_

```
$ gem install pg_online_schema_change
```

Some dependency installation commands need to be added, not everyone is a Ruby expert

The dependencies
```
gem install ougai
gem install thor
gem install pg
gem install pg_query

```

**Comment by asotolongo** [comment]
When a tried to execute `pg-online-schema-change help perform` without this dependencies, i got the following errors:

```
Traceback (most recent call last):
	7: from /usr/local/bin/pg-online-schema-change:23:in `<main>'
	6: from /usr/local/bin/pg-online-schema-change:23:in `load'
	5: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/bin/pg-online-schema-change:4:in `<top (required)>'
	4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	2: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change.rb:4:in `<top (required)>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- ougai (LoadError)
...
Traceback (most recent call last):
	10: from /usr/local/bin/pg-online-schema-change:23:in `<main>'
	 9: from /usr/local/bin/pg-online-schema-change:23:in `load'
	 8: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/bin/pg-online-schema-change:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change.rb:9:in `<top (required)>'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change/cli.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- thor (LoadError)
...
Traceback (most recent call last):
	10: from /usr/local/bin/pg-online-schema-change:23:in `<main>'
	 9: from /usr/local/bin/pg-online-schema-change:23:in `load'
	 8: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/bin/pg-online-schema-change:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change.rb:10:in `<top (required)>'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change/client.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- pg (LoadError)
...
Traceback (most recent call last):
	10: from /usr/local/bin/pg-online-schema-change:23:in `<main>'
	 9: from /usr/local/bin/pg-online-schema-change:23:in `load'
	 8: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/bin/pg-online-schema-change:4:in `<top (required)>'
	 7: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change.rb:11:in `<top (required)>'
	 4: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /var/lib/gems/2.7.0/gems/pg_online_schema_change-0.2.0/lib/pg_online_schema_change/query.rb:1:in `<top (required)>'
	 1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- pg_query (LoadError)

```

After install the dependencies work like charm, Thanks

**Comment by shayonj** [comment]
Oof! yes, I see where its coming from. Thank you @asotolongo . I will have a fix, document update and a new release out. Ideally `gem install pg_online_schem_change` is all you should need. 

Let us know if you have any feedback from using the package 🙌🏾

**Comment by asotolongo** [comment]
Thanks

**Comment by shayonj** [comment]
This is fixed now. Running `gem install pg_online_schema_change` will install all the dependencies too.

<img width="674" alt="image" src="https://user-images.githubusercontent.com/1100970/154985404-c64fc1f9-f827-4dd9-993b-8dfd54dfcc8b.png">


Also have a new listing on Dockerhub now: https://hub.docker.com/r/shayonj/pg-osc

Thanks again for the issue and let us know if there is anything we can help with 🙌🏾
